<?xml version="1.0" encoding="UTF-8"?>
<?Siebel-Property-Set EscapeNames="false"?>

<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tns="http://wservice.cerner.com/" targetNamespace="http://wservice.cerner.com/">
  <import location="http___wservice.cerner.com__Contact_WPS_CERN1.wsdl" namespace="http://wservice.cerner.com/"/>
  <binding name="ContactUpsert" type="tns:ContactUpsert">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/jms"/>
    <operation name="ContactUpsert">
      <soap:operation soapAction="document/http://wservice.cerner.com/:ContactUpsert"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <binding name="ContactQuery" type="tns:ContactQuery">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/jms"/>
    <operation name="ContactQuery">
      <soap:operation soapAction="document/http://wservice.cerner.com/:ContactQuery"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="Contact_spcWPS_spcCERN">
    <port binding="tns:ContactUpsert" name="ContactUpsert">
      <soap:address location="jms:/queue?destination=jms/WSRQ&amp;connectionFactory=jms/WSCF&amp;targetService=ContactUpsert"/>
    </port>
    <port binding="tns:ContactQuery" name="ContactQuery">
      <soap:address location="jms:/queue?destination=jms/WSRQ&amp;connectionFactory=jms/WSCF&amp;targetService=ContactQuery"/>
    </port>
  </service>
</definitions>
