<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="xslt/XSLTransformation2_req_2.map" md5sum="1751da9dc2633a8ee47a84ce48ab6e82" version="1.0.130" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM XML Mapping Editor V1.0.130
*
*   Mapping file:		XSLTransformation2_req_2.map
*   Map declaration(s):	XSLTransformation2_req_2
*   Input file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252Fwservice.cerner.com%252F%257DContact_spcUpsert_spcWPS_spcCERN_ContactUpsert_Output/xpath%3D%252Fbody/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252FSBL_ContactWidget_Lib%252FInvoke%257DContactUpsertResponseMsg/xpath%3D%252Fbody/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:in="wsdl.http://wservice.cerner.com/"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:out="http://SBL_ContactWidget_Lib/Invoke"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:io="http://www.siebel.com/xml/Contact%20WPS%20CERN"
    xmlns:out2="wsdl.http://SBL_ContactWidget_Lib/Invoke"
    xmlns:io2="http://wservice.cerner.com/"
    exclude-result-prefixes="in xalan"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="yes" xalan:indent-amount="2"/>
  <xsl:strip-space elements="*"/>

  <!-- root template  -->
  <xsl:template match="/">
    <xsl:apply-templates select="body" mode="XSLTransformation2_req_2"/>
  </xsl:template>

  <!-- This rule represents an element mapping: "body" to "body".  -->
  <xsl:template match="body"  mode="XSLTransformation2_req_2">
    <body>
      <out:ContactUpsertResponse>
        <io2:Contact_spcUpsert_spcWPS_spcCERN_ContactUpsert_Output>
          <!-- a structural mapping: "io2:Contact_spcUpsert_spcWPS_spcCERN_ContactUpsert_Output/io:ListOfContactWpsCern"(ListOfContactWpsCern) to "io:ListOfContactWpsCern"(ListOfContactWpsCern) -->
          <xsl:copy-of select="io2:Contact_spcUpsert_spcWPS_spcCERN_ContactUpsert_Output/io:ListOfContactWpsCern"/>
        </io2:Contact_spcUpsert_spcWPS_spcCERN_ContactUpsert_Output>
      </out:ContactUpsertResponse>
    </body>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
