<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="xslt/XSLTransformation2_req_3.map" md5sum="e0f7293b8b7ca976037c9fc327f4bb4e" version="1.0.130" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM XML Mapping Editor V1.0.130
*
*   Mapping file:		XSLTransformation2_req_3.map
*   Map declaration(s):	XSLTransformation2_req_3
*   Input file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252Fwservice.cerner.com%252F%257DContact_spcList_spcDelete_spcWPS_spcCERN_ContactListDelete_Output/xpath%3D%252Fbody/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252FSBL_ContactWidget_myContacts_Lib%252FInvoke%257DContactListDeleteResponseMsg/xpath%3D%252Fbody/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:in="wsdl.http://wservice.cerner.com/"
    xmlns:io="http://www.siebel.com/xml/MyContacts%20List%20WPS%20CERN"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:out2="http://SBL_ContactWidget_myContacts_Lib/Invoke"
    xmlns:out="wsdl.http://SBL_ContactWidget_myContacts_Lib/Invoke"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:io2="http://wservice.cerner.com/"
    exclude-result-prefixes="in xalan"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="yes" xalan:indent-amount="2"/>
  <xsl:strip-space elements="*"/>

  <!-- root template  -->
  <xsl:template match="/">
    <xsl:apply-templates select="body" mode="XSLTransformation2_req_3"/>
  </xsl:template>

  <!-- This rule represents an element mapping: "body" to "body".  -->
  <xsl:template match="body"  mode="XSLTransformation2_req_3">
    <body>
      <out2:ContactListDeleteResponse>
        <io2:Contact_spcList_spcDelete_spcWPS_spcCERN_ContactListDelete_Output>
          <!-- a simple data mapping: "io2:Contact_spcList_spcDelete_spcWPS_spcCERN_ContactListDelete_Output/io2:Error_spcCode"(String) to "io2:Error_spcCode"(String) -->
          <io2:Error_spcCode>
            <xsl:value-of select="io2:Contact_spcList_spcDelete_spcWPS_spcCERN_ContactListDelete_Output/io2:Error_spcCode"/>
          </io2:Error_spcCode>
          <!-- a simple data mapping: "io2:Contact_spcList_spcDelete_spcWPS_spcCERN_ContactListDelete_Output/io2:Error_spcMessage"(String) to "io2:Error_spcMessage"(String) -->
          <io2:Error_spcMessage>
            <xsl:value-of select="io2:Contact_spcList_spcDelete_spcWPS_spcCERN_ContactListDelete_Output/io2:Error_spcMessage"/>
          </io2:Error_spcMessage>
          <!-- a structural mapping: "io2:Contact_spcList_spcDelete_spcWPS_spcCERN_ContactListDelete_Output/io:ListOfMycontactsListWpsCern"(ListOfMycontactsListWpsCern) to "io:ListOfMycontactsListWpsCern"(ListOfMycontactsListWpsCern) -->
          <xsl:copy-of select="io2:Contact_spcList_spcDelete_spcWPS_spcCERN_ContactListDelete_Output/io:ListOfMycontactsListWpsCern"/>
        </io2:Contact_spcList_spcDelete_spcWPS_spcCERN_ContactListDelete_Output>
      </out2:ContactListDeleteResponse>
    </body>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
