<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="xslt/ContactUpsertV2InputToSBL.map" md5sum="b127ed35e148597aeea4f26e98e84090" version="7.0.200" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM XML Mapping Editor V7.0.200
*
*   Mapping file:		ContactUpsertV2InputToSBL.map
*   Map declaration(s):	ContactUpsertV2InputToSBL
*   Input file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252FSBL_ContactWidget_Lib%252FInvoke%257DContactUpsertV2RequestMsg/xpath%3D%252Fbody/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252Fwservice.cerner.com%252FV2%257DContact_spcUpsert_spcWPS_spcCERN_ContactUpsert_Input/xpath%3D%252Fbody/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:in="http://www.siebel.com/xml/Contact%20Web%20Access%20WPS%20CERN"
    xmlns:in2="wsdl.http://SBL_ContactWidget_Lib/Invoke"
    xmlns:in3="http://SBL_ContactWidget_Lib/Invoke"
    xmlns:in4="http://www.siebel.com/xml/Contact%20WPS%20CERN"
    xmlns:io="http://www.siebel.com/xml/Contact%20WPS%20CERN_V2"
    xmlns:io2="http://www.w3.org/2003/05/soap-envelope"
    xmlns:io4="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:io3="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:out="wsdl.http://wservice.cerner.com/V2"
    xmlns:io5="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:io6="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:io7="http://www.w3.org/2005/08/addressing"
    xmlns:io8="http://wservice.cerner.com/V2"
    xmlns:map="http://SBL_ContactWidget/xslt/ContactUpsertV2InputToSBL"
    exclude-result-prefixes="in in2 in3 in4 map xalan"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root template  -->
  <xsl:template match="/">
    <xsl:apply-templates select="body" mode="map:ContactUpsertV2InputToSBL"/>
  </xsl:template>

  <!-- This rule represents an element mapping: "body" to "body".  -->
  <xsl:template match="body"  mode="map:ContactUpsertV2InputToSBL">
    <body>
      <io8:Contact_spcUpsert_spcWPS_spcCERN_ContactUpsert_Input>
        <!-- a structural mapping: "in3:ContactUpsertV2/io8:Contact_spcUpsert_spcWPS_spcCERN_ContactUpsert_Input/io:ListOfContactWpsCern"(ListOfContactWpsCern) to "io:ListOfContactWpsCern"(ListOfContactWpsCern) -->
        <xsl:copy-of select="in3:ContactUpsertV2/io8:Contact_spcUpsert_spcWPS_spcCERN_ContactUpsert_Input/io:ListOfContactWpsCern"/>
      </io8:Contact_spcUpsert_spcWPS_spcCERN_ContactUpsert_Input>
    </body>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
