<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="xslt/SBLToContactUpsertResponse.map" md5sum="0636f26a74303951abc1e69f5df05472" version="7.0.200" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM XML Mapping Editor V7.0.200
*
*   Mapping file:		SBLToContactUpsertResponse.map
*   Map declaration(s):	SBLToContactUpsertResponse
*   Input file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252Fwservice.cerner.com%252FV2%257DContact_spcUpsert_spcWPS_spcCERN_ContactUpsert_Output/xpath%3D%252Fbody/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252FSBL_ContactWidget_Lib%252FInvoke%257DContactUpsertResponseMsg/xpath%3D%252Fbody/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:in="wsdl.http://wservice.cerner.com/V2"
    xmlns:in2="http://wservice.cerner.com/V2"
    xmlns:io="http://www.siebel.com/xml/Contact%20WPS%20CERN_V2"
    xmlns:io2="http://www.w3.org/2003/05/soap-envelope"
    xmlns:out="http://www.siebel.com/xml/Contact%20Web%20Access%20WPS%20CERN"
    xmlns:io3="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:out2="wsdl.http://SBL_ContactWidget_Lib/Invoke"
    xmlns:out3="http://SBL_ContactWidget_Lib/Invoke"
    xmlns:io4="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:out4="http://wservice.cerner.com/"
    xmlns:io5="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:io6="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:out5="http://www.siebel.com/xml/Contact%20WPS%20CERN"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:io7="http://www.w3.org/2005/08/addressing"
    xmlns:map="http://SBL_ContactWidget/xslt/SBLToContactUpsertResponse"
    exclude-result-prefixes="in in2 map xalan"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root template  -->
  <xsl:template match="/">
    <xsl:apply-templates select="body" mode="map:SBLToContactUpsertResponse"/>
  </xsl:template>

  <!-- This rule represents an element mapping: "body" to "body".  -->
  <xsl:template match="body"  mode="map:SBLToContactUpsertResponse">
    <body>
      <out3:ContactUpsertResponse>
        <out4:Contact_spcUpsert_spcWPS_spcCERN_ContactUpsert_Output>
          <!-- a structural mapping: "in2:Contact_spcUpsert_spcWPS_spcCERN_ContactUpsert_Output/io:ListOfContactWpsCern"(ListOfContactWpsCern) to "out5:ListOfContactWpsCern"(ListOfContactWpsCern) -->
          <xsl:apply-templates select="in2:Contact_spcUpsert_spcWPS_spcCERN_ContactUpsert_Output/io:ListOfContactWpsCern" mode="localListOfContactWpsCernToListOfContactWpsCern_11899330"/>
        </out4:Contact_spcUpsert_spcWPS_spcCERN_ContactUpsert_Output>
      </out3:ContactUpsertResponse>
    </body>
  </xsl:template>

  <!-- This rule represents an element mapping: "io:ListOfContactWpsCern" to "out5:ListOfContactWpsCern".  -->
  <xsl:template match="io:ListOfContactWpsCern"  mode="localListOfContactWpsCernToListOfContactWpsCern_11899330">
    <out5:ListOfContactWpsCern>
      <!-- a for-each transform: "io:Contact"(Contact) to "out5:Contact"(Contact) -->
      <xsl:apply-templates select="io:Contact" mode="localContactToContact_1949289082"/>
    </out5:ListOfContactWpsCern>
  </xsl:template>

  <!-- This rule represents a for-each transform: "io:Contact" to "out5:Contact".  -->
  <xsl:template match="io:Contact"  mode="localContactToContact_1949289082">
    <out5:Contact>
      <!-- a simple data mapping: "io:Id"(string30) to "out5:Id"(string30) -->
      <xsl:if test="io:Id">
        <out5:Id>
          <xsl:value-of select="io:Id"/>
        </out5:Id>
      </xsl:if>
      <!-- a simple data mapping: "io:MobilePhoneNum"(string) to "out5:MobilePhoneNum"(string) -->
      <xsl:if test="io:MobilePhoneNum">
        <out5:MobilePhoneNum>
          <xsl:value-of select="io:MobilePhoneNum"/>
        </out5:MobilePhoneNum>
      </xsl:if>
      <!-- a simple data mapping: "io:PrimaryEmail"(string50) to "out5:PrimaryEmail"(string50) -->
      <xsl:if test="io:PrimaryEmail">
        <out5:PrimaryEmail>
          <xsl:value-of select="io:PrimaryEmail"/>
        </out5:PrimaryEmail>
      </xsl:if>
      <!-- a simple data mapping: "io:FirstName"(string50) to "out5:FirstName"(string50) -->
      <xsl:if test="io:FirstName">
        <out5:FirstName>
          <xsl:value-of select="io:FirstName"/>
        </out5:FirstName>
      </xsl:if>
      <!-- a simple data mapping: "io:HomePhoneNum"(string) to "out5:HomePhoneNum"(string) -->
      <xsl:if test="io:HomePhoneNum">
        <out5:HomePhoneNum>
          <xsl:value-of select="io:HomePhoneNum"/>
        </out5:HomePhoneNum>
      </xsl:if>
      <!-- a simple data mapping: "io:IntegrationId"(string30) to "out5:IntegrationId"(string30) -->
      <xsl:if test="io:IntegrationId">
        <out5:IntegrationId>
          <xsl:value-of select="io:IntegrationId"/>
        </out5:IntegrationId>
      </xsl:if>
      <!-- a simple data mapping: "io:JobTitle"(string75) to "out5:JobTitle"(string75) -->
      <xsl:if test="io:JobTitle">
        <out5:JobTitle>
          <xsl:value-of select="io:JobTitle"/>
        </out5:JobTitle>
      </xsl:if>
      <!-- a simple data mapping: "io:LastName"(string50) to "out5:LastName"(string50) -->
      <xsl:if test="io:LastName">
        <out5:LastName>
          <xsl:value-of select="io:LastName"/>
        </out5:LastName>
      </xsl:if>
      <!-- a simple data mapping: "io:LoginName"(string50) to "out5:LoginName"(string50) -->
      <xsl:if test="io:LoginName">
        <out5:LoginName>
          <xsl:value-of select="io:LoginName"/>
        </out5:LoginName>
      </xsl:if>
      <!-- a simple data mapping: "io:MrMs"(string15) to "out5:MrMs"(string15) -->
      <xsl:if test="io:MrMs">
        <out5:MrMs>
          <xsl:value-of select="io:MrMs"/>
        </out5:MrMs>
      </xsl:if>
      <!-- a simple data mapping: "io:Mnemonic"(string10) to "out5:Mnemonic"(string10) -->
      <xsl:if test="io:Mnemonic">
        <out5:Mnemonic>
          <xsl:value-of select="io:Mnemonic"/>
        </out5:Mnemonic>
      </xsl:if>
      <!-- a simple data mapping: "io:Role"(string30) to "out5:Role"(string30) -->
      <xsl:if test="io:Role">
        <out5:Role>
          <xsl:value-of select="io:Role"/>
        </out5:Role>
      </xsl:if>
      <!-- a simple data mapping: "io:WorkPhoneNum"(string) to "out5:WorkPhoneNum"(string) -->
      <xsl:if test="io:WorkPhoneNum">
        <out5:WorkPhoneNum>
          <xsl:value-of select="io:WorkPhoneNum"/>
        </out5:WorkPhoneNum>
      </xsl:if>
      <!-- a simple data mapping: "io:WorkPhoneExtension"(string10) to "out5:WorkPhoneExtension"(string10) -->
      <xsl:if test="io:WorkPhoneExtension">
        <out5:WorkPhoneExtension>
          <xsl:value-of select="io:WorkPhoneExtension"/>
        </out5:WorkPhoneExtension>
      </xsl:if>
      <!-- a structural mapping: "io:ListOfContact_Account"(ListOfContact_Account) to "out5:ListOfContact_Account"(ListOfContact_Account) -->
      <xsl:apply-templates select="io:ListOfContact_Account" mode="localListOfContact_AccountToListOfContact_Account_264575396"/>
      <!-- a structural mapping: "io:ListOfContact_BusinessAddress"(ListOfContact_BusinessAddress) to "out5:ListOfContact_BusinessAddress"(ListOfContact_BusinessAddress) -->
      <xsl:apply-templates select="io:ListOfContact_BusinessAddress" mode="localListOfContact_BusinessAddressToListOfContact_BusinessAddress_456805956"/>
      <!-- a structural mapping: "io:ListOfContact_AlternatePhone"(ListOfContact_AlternatePhone) to "out5:ListOfContact_AlternatePhone"(ListOfContact_AlternatePhone) -->
      <xsl:apply-templates select="io:ListOfContact_AlternatePhone" mode="localListOfContact_AlternatePhoneToListOfContact_AlternatePhone_936607070"/>
      <!-- a structural mapping: "io:ListOfAccount"(ListOfAccount) to "out5:ListOfAccount"(ListOfAccount) -->
      <xsl:apply-templates select="io:ListOfAccount" mode="localListOfAccountToListOfAccount_970992565"/>
    </out5:Contact>
  </xsl:template>

  <!-- This rule represents an element mapping: "io:ListOfContact_Account" to "out5:ListOfContact_Account".  -->
  <xsl:template match="io:ListOfContact_Account"  mode="localListOfContact_AccountToListOfContact_Account_264575396">
    <out5:ListOfContact_Account>
      <!-- a for-each transform: "io:Contact_Account"(Contact_Account) to "out5:Contact_Account"(Contact_Account) -->
      <xsl:apply-templates select="io:Contact_Account" mode="localContact_AccountToContact_Account_2102068571"/>
    </out5:ListOfContact_Account>
  </xsl:template>

  <!-- This rule represents a for-each transform: "io:Contact_Account" to "out5:Contact_Account".  -->
  <xsl:template match="io:Contact_Account"  mode="localContact_AccountToContact_Account_2102068571">
    <out5:Contact_Account>
      <!-- a simple data mapping: "io:Account"(string100) to "out5:Account"(string100) -->
      <xsl:if test="io:Account">
        <out5:Account>
          <xsl:value-of select="io:Account"/>
        </out5:Account>
      </xsl:if>
      <!-- a simple data mapping: "io:AccountLocation"(string10) to "out5:AccountLocation"(string10) -->
      <xsl:if test="io:AccountLocation">
        <out5:AccountLocation>
          <xsl:value-of select="io:AccountLocation"/>
        </out5:AccountLocation>
      </xsl:if>
      <!-- a simple data mapping: "io:AccountStatus"(string30) to "out5:AccountStatus"(string30) -->
      <xsl:if test="io:AccountStatus">
        <out5:AccountStatus>
          <xsl:value-of select="io:AccountStatus"/>
        </out5:AccountStatus>
      </xsl:if>
    </out5:Contact_Account>
  </xsl:template>

  <!-- This rule represents an element mapping: "io:ListOfContact_BusinessAddress" to "out5:ListOfContact_BusinessAddress".  -->
  <xsl:template match="io:ListOfContact_BusinessAddress"  mode="localListOfContact_BusinessAddressToListOfContact_BusinessAddress_456805956">
    <out5:ListOfContact_BusinessAddress>
      <!-- a for-each transform: "io:Contact_BusinessAddress"(Contact_BusinessAddress) to "out5:Contact_BusinessAddress"(Contact_BusinessAddress) -->
      <xsl:apply-templates select="io:Contact_BusinessAddress" mode="localContact_BusinessAddressToContact_BusinessAddress_109331203"/>
    </out5:ListOfContact_BusinessAddress>
  </xsl:template>

  <!-- This rule represents a for-each transform: "io:Contact_BusinessAddress" to "out5:Contact_BusinessAddress".  -->
  <xsl:template match="io:Contact_BusinessAddress"  mode="localContact_BusinessAddressToContact_BusinessAddress_109331203">
    <out5:Contact_BusinessAddress>
      <!-- a simple data mapping: "io:City"(string50) to "out5:City"(string50) -->
      <xsl:if test="io:City">
        <out5:City>
          <xsl:value-of select="io:City"/>
        </out5:City>
      </xsl:if>
      <!-- a simple data mapping: "io:Country"(string30) to "out5:Country"(string30) -->
      <xsl:if test="io:Country">
        <out5:Country>
          <xsl:value-of select="io:Country"/>
        </out5:Country>
      </xsl:if>
      <!-- a simple data mapping: "io:ZIPPostalCode"(string30) to "out5:ZIPPostalCode"(string30) -->
      <xsl:if test="io:ZIPPostalCode">
        <out5:ZIPPostalCode>
          <xsl:value-of select="io:ZIPPostalCode"/>
        </out5:ZIPPostalCode>
      </xsl:if>
      <!-- a simple data mapping: "io:StateProvince"(string10) to "out5:StateProvince"(string10) -->
      <xsl:if test="io:StateProvince">
        <out5:StateProvince>
          <xsl:value-of select="io:StateProvince"/>
        </out5:StateProvince>
      </xsl:if>
      <!-- a simple data mapping: "io:ClientAddress"(string200) to "out5:ClientAddress"(string200) -->
      <xsl:if test="io:ClientAddress">
        <out5:ClientAddress>
          <xsl:value-of select="io:ClientAddress"/>
        </out5:ClientAddress>
      </xsl:if>
      <!-- a simple data mapping: "io:AddressLine2"(string100) to "out5:AddressLine2"(string100) -->
      <xsl:if test="io:AddressLine2">
        <out5:AddressLine2>
          <xsl:value-of select="io:AddressLine2"/>
        </out5:AddressLine2>
      </xsl:if>
    </out5:Contact_BusinessAddress>
  </xsl:template>

  <!-- This rule represents an element mapping: "io:ListOfContact_AlternatePhone" to "out5:ListOfContact_AlternatePhone".  -->
  <xsl:template match="io:ListOfContact_AlternatePhone"  mode="localListOfContact_AlternatePhoneToListOfContact_AlternatePhone_936607070">
    <out5:ListOfContact_AlternatePhone>
      <!-- a for-each transform: "io:Contact_AlternatePhone"(Contact_AlternatePhone) to "out5:Contact_AlternatePhone"(Contact_AlternatePhone) -->
      <xsl:apply-templates select="io:Contact_AlternatePhone" mode="localContact_AlternatePhoneToContact_AlternatePhone_1987456917"/>
    </out5:ListOfContact_AlternatePhone>
  </xsl:template>

  <!-- This rule represents a for-each transform: "io:Contact_AlternatePhone" to "out5:Contact_AlternatePhone".  -->
  <xsl:template match="io:Contact_AlternatePhone"  mode="localContact_AlternatePhoneToContact_AlternatePhone_1987456917">
    <out5:Contact_AlternatePhone>
      <!-- a simple data mapping: "io:AlternatePhoneNum"(string) to "out5:AlternatePhoneNum"(string) -->
      <xsl:if test="io:AlternatePhoneNum">
        <out5:AlternatePhoneNum>
          <xsl:value-of select="io:AlternatePhoneNum"/>
        </out5:AlternatePhoneNum>
      </xsl:if>
    </out5:Contact_AlternatePhone>
  </xsl:template>

  <!-- This rule represents an element mapping: "io:ListOfAccount" to "out5:ListOfAccount".  -->
  <xsl:template match="io:ListOfAccount"  mode="localListOfAccountToListOfAccount_970992565">
    <out5:ListOfAccount>
      <!-- a for-each transform: "io:Account"(Account) to "out5:Account"(Account) -->
      <xsl:apply-templates select="io:Account" mode="localAccountToAccount_1088401907"/>
    </out5:ListOfAccount>
  </xsl:template>

  <!-- This rule represents a for-each transform: "io:Account" to "out5:Account".  -->
  <xsl:template match="io:Account"  mode="localAccountToAccount_1088401907">
    <out5:Account>
      <!-- a simple data mapping: "io:StatusofAffiliation"(string30) to "out5:StatusofAffiliation"(string30) -->
      <xsl:if test="io:StatusofAffiliation">
        <out5:StatusofAffiliation>
          <xsl:value-of select="io:StatusofAffiliation"/>
        </out5:StatusofAffiliation>
      </xsl:if>
      <!-- a simple data mapping: "io:JobTitle"(string50) to "out5:JobTitle"(string50) -->
      <xsl:if test="io:JobTitle">
        <out5:JobTitle>
          <xsl:value-of select="io:JobTitle"/>
        </out5:JobTitle>
      </xsl:if>
      <!-- a simple data mapping: "io:Role"(string30) to "out5:Role"(string30) -->
      <xsl:if test="io:Role">
        <out5:Role>
          <xsl:value-of select="io:Role"/>
        </out5:Role>
      </xsl:if>
      <!-- a simple data mapping: "io:Mnemonic"(string10) to "out5:Mnemonic"(string10) -->
      <xsl:if test="io:Mnemonic">
        <out5:Mnemonic>
          <xsl:value-of select="io:Mnemonic"/>
        </out5:Mnemonic>
      </xsl:if>
    </out5:Account>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
