<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions name="InvokeExport1_InvokeHttp_Service" targetNamespace="http://SBL_ContactWidget_Lib/Invoke" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:this="http://SBL_ContactWidget_Lib/Invoke" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:import location="Invoke.wsdl" namespace="http://SBL_ContactWidget_Lib/Invoke"/>
  <wsdl:binding name="InvokeExport1_InvokeHttpBinding" type="this:Invoke">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="ContactUpsert">
      <soap:operation soapAction=""/>
      <wsdl:input name="ContactUpsertRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="ContactUpsertResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="fault1">
        <soap:fault name="fault1" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="ContactQuery">
      <soap:operation soapAction=""/>
      <wsdl:input name="ContactQueryRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="ContactQueryResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="fault1">
        <soap:fault name="fault1" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="ContactAccessQuery">
      <soap:operation soapAction=""/>
      <wsdl:input name="ContactAccessQueryRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="ContactAccessQueryResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="fault1">
        <soap:fault name="fault1" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="ContactQuery_V2">
      <soap:operation soapAction=""/>
      <wsdl:input name="ContactQuery_V2Request">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="ContactQuery_V2Response">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="fault1">
        <soap:fault name="fault1" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="InvokeExport1_InvokeHttpService">
    <wsdl:port binding="this:InvokeExport1_InvokeHttpBinding" name="InvokeExport1_InvokeHttpPort">
      <soap:address location="http://localhost:9080/SBL_ContactWidgetWeb/sca/InvokeExport1"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>