<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="xslt/XSLTransformation1_req_1.map" md5sum="c5a00ce4d13d2ba350c67bc7b5fbc38b" version="7.0.200" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM XML Mapping Editor V7.0.200
*
*   Mapping file:		XSLTransformation1_req_1.map
*   Map declaration(s):	XSLTransformation1_req_1
*   Input file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252FSBL_Dedup_Lib%252FInvoke%257DDedupRequestMsg/xpath%3D%252Fbody/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252Fwservice.cerner.com%257DDeduplication_spcProxy_spcCERN_Dedup_Input/xpath%3D%252Fbody/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:in="http://SBL_Dedup_Lib"
    xmlns:in2="http://SBL_Dedup_Lib/Invoke"
    xmlns:in3="wsdl.http://SBL_Dedup_Lib/Invoke"
    xmlns:in4="http://www.siebel.com/xml/Deduplication%20External%20Output%20CERN"
    xmlns:io="http://www.w3.org/2003/05/soap-envelope"
    xmlns:io3="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:io2="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:out="wsdl.http://wservice.cerner.com"
    xmlns:io4="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:io5="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:out2="http://wservice.cerner.com"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:io6="http://www.w3.org/2005/08/addressing"
    xmlns:map="http://SBL_Dedup/xslt/XSLTransformation1_req_1"
    exclude-result-prefixes="in in2 in3 in4 map xalan"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root template  -->
  <xsl:template match="/">
    <xsl:apply-templates select="body" mode="map:XSLTransformation1_req_1"/>
  </xsl:template>

  <!-- This rule represents an element mapping: "body" to "body".  -->
  <xsl:template match="body"  mode="map:XSLTransformation1_req_1">
    <body>
      <out2:Deduplication_spcProxy_spcCERN_Dedup_Input>
        <!-- a simple data mapping: "in2:Dedup/Deduplication_spcProxy_spcCERN_Dedup_Input/FirstName"(string) to "out2:FirstName"(string) -->
        <out2:FirstName>
          <xsl:value-of select="in2:Dedup/Deduplication_spcProxy_spcCERN_Dedup_Input/FirstName"/>
        </out2:FirstName>
        <!-- a simple data mapping: "in2:Dedup/Deduplication_spcProxy_spcCERN_Dedup_Input/WorkPhoneNum"(string) to "out2:WorkPhoneNum"(string) -->
        <out2:WorkPhoneNum>
          <xsl:value-of select="in2:Dedup/Deduplication_spcProxy_spcCERN_Dedup_Input/WorkPhoneNum"/>
        </out2:WorkPhoneNum>
        <!-- a simple data mapping: "in2:Dedup/Deduplication_spcProxy_spcCERN_Dedup_Input/Account"(string) to "out2:Account"(string) -->
        <out2:Account>
          <xsl:value-of select="in2:Dedup/Deduplication_spcProxy_spcCERN_Dedup_Input/Account"/>
        </out2:Account>
        <!-- a simple data mapping: "in2:Dedup/Deduplication_spcProxy_spcCERN_Dedup_Input/_XML_spcString"(string) to "out2:_XML_spcString"(string) -->
        <out2:_XML_spcString>
          <xsl:value-of select="in2:Dedup/Deduplication_spcProxy_spcCERN_Dedup_Input/_XML_spcString"/>
        </out2:_XML_spcString>
        <!-- a simple data mapping: "in2:Dedup/Deduplication_spcProxy_spcCERN_Dedup_Input/EmailAddress"(string) to "out2:EmailAddress"(string) -->
        <out2:EmailAddress>
          <xsl:value-of select="in2:Dedup/Deduplication_spcProxy_spcCERN_Dedup_Input/EmailAddress"/>
        </out2:EmailAddress>
        <!-- a simple data mapping: "in2:Dedup/Deduplication_spcProxy_spcCERN_Dedup_Input/LastName"(string) to "out2:LastName"(string) -->
        <out2:LastName>
          <xsl:value-of select="in2:Dedup/Deduplication_spcProxy_spcCERN_Dedup_Input/LastName"/>
        </out2:LastName>
      </out2:Deduplication_spcProxy_spcCERN_Dedup_Input>
    </body>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
