<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="xslt/XSLTransformation2_req_2.map" md5sum="a36bccc5fed87ec1d0d5f9676281a373" version="1.0.130" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM XML Mapping Editor V1.0.130
*
*   Mapping file:		XSLTransformation2_req_2.map
*   Map declaration(s):	XSLTransformation2_req_2
*   Input file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252Fwservice.cerner.com%252F%257DContact_spcList_spcQuery_spcWPS_spcCERN_ContactListQuery_Output/xpath%3D%252Fbody/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252FSBL_ContactWidget_myContacts_Lib%252FInvoke%257DContactListQueryResponseMsg/xpath%3D%252Fbody/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:in="wsdl.http://wservice.cerner.com/"
    xmlns:io="http://www.siebel.com/xml/Contact%20List%20WPS%20CERN"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:out2="http://SBL_ContactWidget_myContacts_Lib/Invoke"
    xmlns:out="wsdl.http://SBL_ContactWidget_myContacts_Lib/Invoke"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:io2="http://wservice.cerner.com/"
    exclude-result-prefixes="in xalan"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="yes" xalan:indent-amount="2"/>
  <xsl:strip-space elements="*"/>

  <!-- root template  -->
  <xsl:template match="/">
    <xsl:apply-templates select="body" mode="XSLTransformation2_req_2"/>
  </xsl:template>

  <!-- This rule represents an element mapping: "body" to "body".  -->
  <xsl:template match="body"  mode="XSLTransformation2_req_2">
    <body>
      <out2:ContactListQueryResponse>
        <io2:Contact_spcList_spcQuery_spcWPS_spcCERN_ContactListQuery_Output>
          <!-- a simple data mapping: "io2:Contact_spcList_spcQuery_spcWPS_spcCERN_ContactListQuery_Output/io2:Error_spcCode"(String) to "io2:Error_spcCode"(String) -->
          <io2:Error_spcCode>
            <xsl:value-of select="io2:Contact_spcList_spcQuery_spcWPS_spcCERN_ContactListQuery_Output/io2:Error_spcCode"/>
          </io2:Error_spcCode>
          <!-- a simple data mapping: "io2:Contact_spcList_spcQuery_spcWPS_spcCERN_ContactListQuery_Output/io2:Error_spcMessage"(String) to "io2:Error_spcMessage"(String) -->
          <io2:Error_spcMessage>
            <xsl:value-of select="io2:Contact_spcList_spcQuery_spcWPS_spcCERN_ContactListQuery_Output/io2:Error_spcMessage"/>
          </io2:Error_spcMessage>
          <!-- a structural mapping: "io2:Contact_spcList_spcQuery_spcWPS_spcCERN_ContactListQuery_Output/io:ListOfContactListWpsCern"(ListOfContactListWpsCern) to "io:ListOfContactListWpsCern"(ListOfContactListWpsCern) -->
          <xsl:copy-of select="io2:Contact_spcList_spcQuery_spcWPS_spcCERN_ContactListQuery_Output/io:ListOfContactListWpsCern"/>
        </io2:Contact_spcList_spcQuery_spcWPS_spcCERN_ContactListQuery_Output>
      </out2:ContactListQueryResponse>
    </body>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
