<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="xslt/ContactQueryV2InputToSBL.map" md5sum="8d3541ce7c2aedbd2350f73fc8ef1659" version="7.0.200" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM XML Mapping Editor V7.0.200
*
*   Mapping file:		ContactQueryV2InputToSBL.map
*   Map declaration(s):	ContactQueryV2InputToSBL
*   Input file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252FSBL_ContactWidget_Lib%252FInvoke%257DContactQuery_V2RequestMsg/xpath%3D%252Fbody/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252Fwservice.cerner.com%252F%257DContact_spcQuery_spcWPS_spcCERN_ContactQuery_Input/xpath%3D%252Fbody/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:in="http://www.siebel.com/xml/Contact%20Web%20Access%20WPS%20CERN"
    xmlns:in2="wsdl.http://SBL_ContactWidget_Lib/Invoke"
    xmlns:in3="http://SBL_ContactWidget_Lib/Invoke"
    xmlns:in4="http://www.siebel.com/xml/Contact%20WPS%20CERN"
    xmlns:io="http://www.siebel.com/xml/Contact%20WPS%20CERN_V2"
    xmlns:io2="http://www.w3.org/2003/05/soap-envelope"
    xmlns:io5="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:io4="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:io3="http://wservice.cerner.com/"
    xmlns:io6="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:io7="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:out="wsdl.http://wservice.cerner.com/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:io8="http://www.w3.org/2005/08/addressing"
    xmlns:map="http://SBL_ContactWidget/xslt/ContactQueryInputToSBL"
    exclude-result-prefixes="in in2 in3 in4 map xalan"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root template  -->
  <xsl:template match="/">
    <xsl:apply-templates select="body" mode="map:ContactQueryV2InputToSBL"/>
  </xsl:template>

  <!-- This rule represents an element mapping: "body" to "body".  -->
  <xsl:template match="body"  mode="map:ContactQueryV2InputToSBL">
    <body>
      <io3:Contact_spcQuery_spcWPS_spcCERN_ContactQuery_Input_V2>
        <!-- a simple data mapping: "in3:ContactQuery_V2/io3:Contact_spcQuery_spcWPS_spcCERN_ContactQuery_Input_V2/io3:ComplexSearchSpec"(string) to "io3:ComplexSearchSpec"(string) -->
        <io3:ComplexSearchSpec>
          <xsl:value-of select="in3:ContactQuery_V2/io3:Contact_spcQuery_spcWPS_spcCERN_ContactQuery_Input_V2/io3:ComplexSearchSpec"/>
        </io3:ComplexSearchSpec>
        <!-- a structural mapping: "in3:ContactQuery_V2/io3:Contact_spcQuery_spcWPS_spcCERN_ContactQuery_Input_V2/io:ListOfContactWpsCern"(ListOfContactWpsCern) to "io:ListOfContactWpsCern"(ListOfContactWpsCern) -->
        <xsl:copy-of select="in3:ContactQuery_V2/io3:Contact_spcQuery_spcWPS_spcCERN_ContactQuery_Input_V2/io:ListOfContactWpsCern"/>
      </io3:Contact_spcQuery_spcWPS_spcCERN_ContactQuery_Input_V2>
    </body>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
