<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="xslt/SBL_to_ContactQuery_V2_Response.map" md5sum="f4bee57ae5f3927169ae5f1da4632960" version="7.0.200" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM XML Mapping Editor V7.0.200
*
*   Mapping file:		SBL_to_ContactQuery_V2_Response.map
*   Map declaration(s):	SBL_to_ContactQuery_V2_Response
*   Input file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252Fwservice.cerner.com%252F%257DContact_spcQuery_spcWPS_spcCERN_ContactQuery_Output/xpath%3D%252Fbody/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252FSBL_ContactWidget_Lib%252FInvoke%257DContactQuery_V2ResponseMsg/xpath%3D%252Fbody/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:in="wsdl.http://wservice.cerner.com/"
    xmlns:io="http://www.siebel.com/xml/Contact%20WPS%20CERN_V2"
    xmlns:io2="http://www.w3.org/2003/05/soap-envelope"
    xmlns:out="http://www.siebel.com/xml/Contact%20Web%20Access%20WPS%20CERN"
    xmlns:io3="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:out2="wsdl.http://SBL_ContactWidget_Lib/Invoke"
    xmlns:out3="http://SBL_ContactWidget_Lib/Invoke"
    xmlns:io4="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:io5="http://wservice.cerner.com/"
    xmlns:io6="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:io7="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:out4="http://www.siebel.com/xml/Contact%20WPS%20CERN"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:io8="http://www.w3.org/2005/08/addressing"
    xmlns:map="http://SBL_ContactWidget/xslt/SBL_to_ContactQuery_V2_Response"
    exclude-result-prefixes="in map xalan"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root template  -->
  <xsl:template match="/">
    <xsl:apply-templates select="body" mode="map:SBL_to_ContactQuery_V2_Response"/>
  </xsl:template>

  <!-- This rule represents an element mapping: "body" to "body".  -->
  <xsl:template match="body"  mode="map:SBL_to_ContactQuery_V2_Response">
    <body>
      <out3:ContactQuery_V2Response>
        <io5:Contact_spcQuery_spcWPS_spcCERN_ContactQuery_Output_V2>
          <!-- a simple data mapping: "io5:Contact_spcQuery_spcWPS_spcCERN_ContactQuery_Output_V2/io5:Error_spcCode"(string) to "io5:Error_spcCode"(string) -->
          <io5:Error_spcCode>
            <xsl:value-of select="io5:Contact_spcQuery_spcWPS_spcCERN_ContactQuery_Output_V2/io5:Error_spcCode"/>
          </io5:Error_spcCode>
          <!-- a simple data mapping: "io5:Contact_spcQuery_spcWPS_spcCERN_ContactQuery_Output_V2/io5:Error_spcMessage"(string) to "io5:Error_spcMessage"(string) -->
          <io5:Error_spcMessage>
            <xsl:value-of select="io5:Contact_spcQuery_spcWPS_spcCERN_ContactQuery_Output_V2/io5:Error_spcMessage"/>
          </io5:Error_spcMessage>
          <!-- a structural mapping: "io5:Contact_spcQuery_spcWPS_spcCERN_ContactQuery_Output_V2/io:ListOfContactWpsCern"(ListOfContactWpsCern) to "io:ListOfContactWpsCern"(ListOfContactWpsCern) -->
          <xsl:copy-of select="io5:Contact_spcQuery_spcWPS_spcCERN_ContactQuery_Output_V2/io:ListOfContactWpsCern"/>
        </io5:Contact_spcQuery_spcWPS_spcCERN_ContactQuery_Output_V2>
      </out3:ContactQuery_V2Response>
    </body>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
