<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="xslt/AccessQuery_Out.map" md5sum="a290713596496503b6bae2648ac724a5" version="7.0.200" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM XML Mapping Editor V7.0.200
*
*   Mapping file:		AccessQuery_Out.map
*   Map declaration(s):	AccessQuery_Out
*   Input file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252Fwservice.cerner.com%257DContact_spcWeb_spcAccess_spcQuery_spcWPS_spcCERN_CNTCT_WA_QRY_Output/xpath%3D%252Fbody/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252FSBL_ContactWidget_Lib%252FInvoke%257DContactAccessQueryResponseMsg/xpath%3D%252Fbody/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:in="wsdl.http://wservice.cerner.com"
    xmlns:io="http://www.w3.org/2003/05/soap-envelope"
    xmlns:io2="http://www.siebel.com/xml/Contact%20Web%20Access%20WPS%20CERN"
    xmlns:io3="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:out2="wsdl.http://SBL_ContactWidget_Lib/Invoke"
    xmlns:out="http://SBL_ContactWidget_Lib/Invoke"
    xmlns:io4="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:io5="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:io6="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:out3="http://www.siebel.com/xml/Contact%20WPS%20CERN"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:io7="http://wservice.cerner.com"
    xmlns:io8="http://www.w3.org/2005/08/addressing"
    xmlns:map="http://SBL_ContactWidget/xslt/AccessQuery_Out"
    exclude-result-prefixes="in map xalan"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root template  -->
  <xsl:template match="/">
    <xsl:apply-templates select="body" mode="map:AccessQuery_Out"/>
  </xsl:template>

  <!-- This rule represents an element mapping: "body" to "body".  -->
  <xsl:template match="body"  mode="map:AccessQuery_Out">
    <body>
      <out:ContactAccessQueryResponse>
        <!-- a structural mapping: "io7:Contact_spcWeb_spcAccess_spcQuery_spcWPS_spcCERN_CNTCT_WA_QRY_Output"(<Anonymous>) to "io7:Contact_spcWeb_spcAccess_spcQuery_spcWPS_spcCERN_CNTCT_WA_QRY_Output"(<Anonymous>) -->
        <xsl:copy-of select="io7:Contact_spcWeb_spcAccess_spcQuery_spcWPS_spcCERN_CNTCT_WA_QRY_Output"/>
      </out:ContactAccessQueryResponse>
    </body>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
