<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="xslt/ContactUpsert_Input_to_SBL.map" md5sum="e17a6bb8eb53b6055be08dd64fc0e6f9" version="7.0.200" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM XML Mapping Editor V7.0.200
*
*   Mapping file:		ContactUpsert_Input_to_SBL.map
*   Map declaration(s):	ContactUpsert_Input_to_SBL
*   Input file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252FSBL_ContactWidget_Lib%252FInvoke%257DContactUpsertRequestMsg/xpath%3D%252Fbody/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252Fwservice.cerner.com%252F%257DContact_spcUpsert_spcWPS_spcCERN_ContactUpsert_Input/xpath%3D%252Fbody/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:in="http://www.siebel.com/xml/Contact%20Web%20Access%20WPS%20CERN"
    xmlns:in2="wsdl.http://SBL_ContactWidget_Lib/Invoke"
    xmlns:in3="http://SBL_ContactWidget_Lib/Invoke"
    xmlns:in4="http://www.siebel.com/xml/Contact%20WPS%20CERN"
    xmlns:io="http://www.siebel.com/xml/Contact%20WPS%20CERN_V2"
    xmlns:io2="http://www.w3.org/2003/05/soap-envelope"
    xmlns:io5="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:io4="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:io3="http://wservice.cerner.com/"
    xmlns:io6="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:io7="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:out="wsdl.http://wservice.cerner.com/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:io8="http://www.w3.org/2005/08/addressing"
    xmlns:map="http://SBL_ContactWidget/xslt/XSLTransformation1_req_2"
    exclude-result-prefixes="in in2 in3 in4 map xalan"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root template  -->
  <xsl:template match="/">
    <xsl:apply-templates select="body" mode="map:ContactUpsert_Input_to_SBL"/>
  </xsl:template>

  <!-- This rule represents an element mapping: "body" to "body".  -->
  <xsl:template match="body"  mode="map:ContactUpsert_Input_to_SBL">
    <body>
      <io3:Contact_spcUpsert_spcWPS_spcCERN_ContactUpsert_Input_V2>
        <!-- a structural mapping: "in3:ContactUpsert/io3:Contact_spcUpsert_spcWPS_spcCERN_ContactUpsert_Input/in4:ListOfContactWpsCern"(ListOfContactWpsCern) to "io:ListOfContactWpsCern"(ListOfContactWpsCern) -->
        <xsl:apply-templates select="in3:ContactUpsert/io3:Contact_spcUpsert_spcWPS_spcCERN_ContactUpsert_Input/in4:ListOfContactWpsCern" mode="localListOfContactWpsCernToListOfContactWpsCern_1193422000"/>
      </io3:Contact_spcUpsert_spcWPS_spcCERN_ContactUpsert_Input_V2>
    </body>
  </xsl:template>

  <!-- This rule represents an element mapping: "in4:ListOfContactWpsCern" to "io:ListOfContactWpsCern".  -->
  <xsl:template match="in4:ListOfContactWpsCern"  mode="localListOfContactWpsCernToListOfContactWpsCern_1193422000">
    <io:ListOfContactWpsCern>
      <!-- a for-each transform: "in4:Contact"(Contact) to "io:Contact"(Contact) -->
      <xsl:apply-templates select="in4:Contact" mode="localContactToContact_1283529296"/>
    </io:ListOfContactWpsCern>
  </xsl:template>

  <!-- This rule represents a for-each transform: "in4:Contact" to "io:Contact".  -->
  <xsl:template match="in4:Contact"  mode="localContactToContact_1283529296">
    <io:Contact>
      <!-- a simple data mapping: "in4:Id"(string30) to "io:Id"(string30) -->
      <xsl:if test="in4:Id">
        <io:Id>
          <xsl:value-of select="in4:Id"/>
        </io:Id>
      </xsl:if>
      <!-- a simple data mapping: "in4:MobilePhoneNum"(string) to "io:MobilePhoneNum"(string) -->
      <xsl:if test="in4:MobilePhoneNum">
        <io:MobilePhoneNum>
          <xsl:value-of select="in4:MobilePhoneNum"/>
        </io:MobilePhoneNum>
      </xsl:if>
      <!-- a simple data mapping: "in4:PrimaryEmail"(string50) to "io:PrimaryEmail"(string50) -->
      <xsl:if test="in4:PrimaryEmail">
        <io:PrimaryEmail>
          <xsl:value-of select="in4:PrimaryEmail"/>
        </io:PrimaryEmail>
      </xsl:if>
      <!-- a simple data mapping: "in4:FirstName"(string50) to "io:FirstName"(string50) -->
      <xsl:if test="in4:FirstName">
        <io:FirstName>
          <xsl:value-of select="in4:FirstName"/>
        </io:FirstName>
      </xsl:if>
      <!-- a simple data mapping: "in4:HomePhoneNum"(string) to "io:HomePhoneNum"(string) -->
      <xsl:if test="in4:HomePhoneNum">
        <io:HomePhoneNum>
          <xsl:value-of select="in4:HomePhoneNum"/>
        </io:HomePhoneNum>
      </xsl:if>
      <!-- a simple data mapping: "in4:IntegrationId"(string30) to "io:IntegrationId"(string30) -->
      <xsl:if test="in4:IntegrationId">
        <io:IntegrationId>
          <xsl:value-of select="in4:IntegrationId"/>
        </io:IntegrationId>
      </xsl:if>
      <!-- a simple data mapping: "in4:JobTitle"(string75) to "io:JobTitle"(string75) -->
      <xsl:if test="in4:JobTitle">
        <io:JobTitle>
          <xsl:value-of select="in4:JobTitle"/>
        </io:JobTitle>
      </xsl:if>
      <!-- a simple data mapping: "in4:LastName"(string50) to "io:LastName"(string50) -->
      <xsl:if test="in4:LastName">
        <io:LastName>
          <xsl:value-of select="in4:LastName"/>
        </io:LastName>
      </xsl:if>
      <!-- a simple data mapping: "in4:LoginName"(string50) to "io:LoginName"(string50) -->
      <xsl:if test="in4:LoginName">
        <io:LoginName>
          <xsl:value-of select="in4:LoginName"/>
        </io:LoginName>
      </xsl:if>
      <!-- a simple data mapping: "in4:MrMs"(string15) to "io:MrMs"(string15) -->
      <xsl:if test="in4:MrMs">
        <io:MrMs>
          <xsl:value-of select="in4:MrMs"/>
        </io:MrMs>
      </xsl:if>
      <!-- a simple data mapping: "in4:Mnemonic"(string10) to "io:Mnemonic"(string10) -->
      <xsl:if test="in4:Mnemonic">
        <io:Mnemonic>
          <xsl:value-of select="in4:Mnemonic"/>
        </io:Mnemonic>
      </xsl:if>
      <!-- a simple data mapping: "in4:Role"(string30) to "io:Role"(string30) -->
      <xsl:if test="in4:Role">
        <io:Role>
          <xsl:value-of select="in4:Role"/>
        </io:Role>
      </xsl:if>
      <!-- a simple data mapping: "in4:WorkPhoneNum"(string) to "io:WorkPhoneNum"(string) -->
      <xsl:if test="in4:WorkPhoneNum">
        <io:WorkPhoneNum>
          <xsl:value-of select="in4:WorkPhoneNum"/>
        </io:WorkPhoneNum>
      </xsl:if>
      <!-- a simple data mapping: "in4:WorkPhoneExtension"(string10) to "io:WorkPhoneExtension"(string10) -->
      <xsl:if test="in4:WorkPhoneExtension">
        <io:WorkPhoneExtension>
          <xsl:value-of select="in4:WorkPhoneExtension"/>
        </io:WorkPhoneExtension>
      </xsl:if>
      <!-- a structural mapping: "in4:ListOfContact_Account"(ListOfContact_Account) to "io:ListOfContact_Account"(ListOfContact_Account) -->
      <xsl:apply-templates select="in4:ListOfContact_Account" mode="localListOfContact_AccountToListOfContact_Account_1664046252"/>
      <!-- a structural mapping: "in4:ListOfContact_BusinessAddress"(ListOfContact_BusinessAddress) to "io:ListOfContact_BusinessAddress"(ListOfContact_BusinessAddress) -->
      <xsl:apply-templates select="in4:ListOfContact_BusinessAddress" mode="localListOfContact_BusinessAddressToListOfContact_BusinessAddress_1089134214"/>
      <!-- a structural mapping: "in4:ListOfContact_AlternatePhone"(ListOfContact_AlternatePhone) to "io:ListOfContact_AlternatePhone"(ListOfContact_AlternatePhone) -->
      <xsl:apply-templates select="in4:ListOfContact_AlternatePhone" mode="localListOfContact_AlternatePhoneToListOfContact_AlternatePhone_320718296"/>
      <!-- a structural mapping: "in4:ListOfAccount"(ListOfAccount) to "io:ListOfAccount"(ListOfAccount) -->
      <xsl:apply-templates select="in4:ListOfAccount" mode="localListOfAccountToListOfAccount_1110105387"/>
    </io:Contact>
  </xsl:template>

  <!-- This rule represents an element mapping: "in4:ListOfContact_Account" to "io:ListOfContact_Account".  -->
  <xsl:template match="in4:ListOfContact_Account"  mode="localListOfContact_AccountToListOfContact_Account_1664046252">
    <io:ListOfContact_Account>
      <!-- a for-each transform: "in4:Contact_Account"(Contact_Account) to "io:Contact_Account"(Contact_Account) -->
      <xsl:apply-templates select="in4:Contact_Account" mode="localContact_AccountToContact_Account_337675882"/>
    </io:ListOfContact_Account>
  </xsl:template>

  <!-- This rule represents a for-each transform: "in4:Contact_Account" to "io:Contact_Account".  -->
  <xsl:template match="in4:Contact_Account"  mode="localContact_AccountToContact_Account_337675882">
    <io:Contact_Account>
      <!-- a simple data mapping: "in4:Account"(string100) to "io:Account"(string100) -->
      <xsl:if test="in4:Account">
        <io:Account>
          <xsl:value-of select="in4:Account"/>
        </io:Account>
      </xsl:if>
      <!-- a simple data mapping: "in4:AccountLocation"(string10) to "io:AccountLocation"(string10) -->
      <xsl:if test="in4:AccountLocation">
        <io:AccountLocation>
          <xsl:value-of select="in4:AccountLocation"/>
        </io:AccountLocation>
      </xsl:if>
      <!-- a simple data mapping: "in4:AccountStatus"(string30) to "io:AccountStatus"(string30) -->
      <xsl:if test="in4:AccountStatus">
        <io:AccountStatus>
          <xsl:value-of select="in4:AccountStatus"/>
        </io:AccountStatus>
      </xsl:if>
    </io:Contact_Account>
  </xsl:template>

  <!-- This rule represents an element mapping: "in4:ListOfContact_BusinessAddress" to "io:ListOfContact_BusinessAddress".  -->
  <xsl:template match="in4:ListOfContact_BusinessAddress"  mode="localListOfContact_BusinessAddressToListOfContact_BusinessAddress_1089134214">
    <io:ListOfContact_BusinessAddress>
      <!-- a for-each transform: "in4:Contact_BusinessAddress"(Contact_BusinessAddress) to "io:Contact_BusinessAddress"(Contact_BusinessAddress) -->
      <xsl:apply-templates select="in4:Contact_BusinessAddress" mode="localContact_BusinessAddressToContact_BusinessAddress_1872242492"/>
    </io:ListOfContact_BusinessAddress>
  </xsl:template>

  <!-- This rule represents a for-each transform: "in4:Contact_BusinessAddress" to "io:Contact_BusinessAddress".  -->
  <xsl:template match="in4:Contact_BusinessAddress"  mode="localContact_BusinessAddressToContact_BusinessAddress_1872242492">
    <io:Contact_BusinessAddress>
      <!-- a simple data mapping: "in4:City"(string50) to "io:City"(string50) -->
      <xsl:if test="in4:City">
        <io:City>
          <xsl:value-of select="in4:City"/>
        </io:City>
      </xsl:if>
      <!-- a simple data mapping: "in4:Country"(string30) to "io:Country"(string30) -->
      <xsl:if test="in4:Country">
        <io:Country>
          <xsl:value-of select="in4:Country"/>
        </io:Country>
      </xsl:if>
      <!-- a simple data mapping: "in4:ZIPPostalCode"(string30) to "io:ZIPPostalCode"(string30) -->
      <xsl:if test="in4:ZIPPostalCode">
        <io:ZIPPostalCode>
          <xsl:value-of select="in4:ZIPPostalCode"/>
        </io:ZIPPostalCode>
      </xsl:if>
      <!-- a simple data mapping: "in4:StateProvince"(string10) to "io:StateProvince"(string10) -->
      <xsl:if test="in4:StateProvince">
        <io:StateProvince>
          <xsl:value-of select="in4:StateProvince"/>
        </io:StateProvince>
      </xsl:if>
      <!-- a simple data mapping: "in4:ClientAddress"(string200) to "io:ClientAddress"(string200) -->
      <xsl:if test="in4:ClientAddress">
        <io:ClientAddress>
          <xsl:value-of select="in4:ClientAddress"/>
        </io:ClientAddress>
      </xsl:if>
      <!-- a simple data mapping: "in4:AddressLine2"(string100) to "io:AddressLine2"(string100) -->
      <xsl:if test="in4:AddressLine2">
        <io:AddressLine2>
          <xsl:value-of select="in4:AddressLine2"/>
        </io:AddressLine2>
      </xsl:if>
    </io:Contact_BusinessAddress>
  </xsl:template>

  <!-- This rule represents an element mapping: "in4:ListOfContact_AlternatePhone" to "io:ListOfContact_AlternatePhone".  -->
  <xsl:template match="in4:ListOfContact_AlternatePhone"  mode="localListOfContact_AlternatePhoneToListOfContact_AlternatePhone_320718296">
    <io:ListOfContact_AlternatePhone>
      <!-- a for-each transform: "in4:Contact_AlternatePhone"(Contact_AlternatePhone) to "io:Contact_AlternatePhone"(Contact_AlternatePhone) -->
      <xsl:apply-templates select="in4:Contact_AlternatePhone" mode="localContact_AlternatePhoneToContact_AlternatePhone_281467625"/>
    </io:ListOfContact_AlternatePhone>
  </xsl:template>

  <!-- This rule represents a for-each transform: "in4:Contact_AlternatePhone" to "io:Contact_AlternatePhone".  -->
  <xsl:template match="in4:Contact_AlternatePhone"  mode="localContact_AlternatePhoneToContact_AlternatePhone_281467625">
    <io:Contact_AlternatePhone>
      <!-- a simple data mapping: "in4:AlternatePhoneNum"(string) to "io:AlternatePhoneNum"(string) -->
      <xsl:if test="in4:AlternatePhoneNum">
        <io:AlternatePhoneNum>
          <xsl:value-of select="in4:AlternatePhoneNum"/>
        </io:AlternatePhoneNum>
      </xsl:if>
    </io:Contact_AlternatePhone>
  </xsl:template>

  <!-- This rule represents an element mapping: "in4:ListOfAccount" to "io:ListOfAccount".  -->
  <xsl:template match="in4:ListOfAccount"  mode="localListOfAccountToListOfAccount_1110105387">
    <io:ListOfAccount>
      <!-- a for-each transform: "in4:Account"(Account) to "io:Account"(Account) -->
      <xsl:apply-templates select="in4:Account" mode="localAccountToAccount_306077367"/>
    </io:ListOfAccount>
  </xsl:template>

  <!-- This rule represents a for-each transform: "in4:Account" to "io:Account".  -->
  <xsl:template match="in4:Account"  mode="localAccountToAccount_306077367">
    <io:Account>
      <!-- a simple data mapping: "in4:StatusofAffiliation"(string30) to "io:StatusofAffiliation"(string30) -->
      <xsl:if test="in4:StatusofAffiliation">
        <io:StatusofAffiliation>
          <xsl:value-of select="in4:StatusofAffiliation"/>
        </io:StatusofAffiliation>
      </xsl:if>
      <!-- a simple data mapping: "in4:JobTitle"(string50) to "io:JobTitle"(string50) -->
      <xsl:if test="in4:JobTitle">
        <io:JobTitle>
          <xsl:value-of select="in4:JobTitle"/>
        </io:JobTitle>
      </xsl:if>
      <!-- a simple data mapping: "in4:Role"(string30) to "io:Role"(string30) -->
      <xsl:if test="in4:Role">
        <io:Role>
          <xsl:value-of select="in4:Role"/>
        </io:Role>
      </xsl:if>
      <!-- a simple data mapping: "in4:Mnemonic"(string10) to "io:Mnemonic"(string10) -->
      <xsl:if test="in4:Mnemonic">
        <io:Mnemonic>
          <xsl:value-of select="in4:Mnemonic"/>
        </io:Mnemonic>
      </xsl:if>
    </io:Account>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
