<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="xslt/XSLTransformation1_req_2.map" md5sum="205936e340a03d648c76b78251889f5d" version="1.0.130" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM XML Mapping Editor V1.0.130
*
*   Mapping file:		XSLTransformation1_req_2.map
*   Map declaration(s):	XSLTransformation1_req_2
*   Input file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252FSBL_ContactWidget_myContacts_Lib%252FInvoke%257DContactListQueryRequestMsg/xpath%3D%252Fbody/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252Fwservice.cerner.com%252F%257DContact_spcList_spcQuery_spcWPS_spcCERN_ContactListQuery_Input/xpath%3D%252Fbody/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:in2="http://SBL_ContactWidget_myContacts_Lib/Invoke"
    xmlns:in="wsdl.http://SBL_ContactWidget_myContacts_Lib/Invoke"
    xmlns:io="http://www.siebel.com/xml/Contact%20List%20WPS%20CERN"
    xmlns:out="wsdl.http://wservice.cerner.com/"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:io2="http://wservice.cerner.com/"
    exclude-result-prefixes="in2 in xalan"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="yes" xalan:indent-amount="2"/>
  <xsl:strip-space elements="*"/>

  <!-- root template  -->
  <xsl:template match="/">
    <xsl:apply-templates select="body" mode="XSLTransformation1_req_2"/>
  </xsl:template>

  <!-- This rule represents an element mapping: "body" to "body".  -->
  <xsl:template match="body"  mode="XSLTransformation1_req_2">
    <body>
      <io2:Contact_spcList_spcQuery_spcWPS_spcCERN_ContactListQuery_Input>
        <!-- a simple data mapping: "in2:ContactListQuery/io2:Contact_spcList_spcQuery_spcWPS_spcCERN_ContactListQuery_Input/io2:ComplexSearchSpec"(String) to "io2:ComplexSearchSpec"(String) -->
        <io2:ComplexSearchSpec>
          <xsl:value-of select="in2:ContactListQuery/io2:Contact_spcList_spcQuery_spcWPS_spcCERN_ContactListQuery_Input/io2:ComplexSearchSpec"/>
        </io2:ComplexSearchSpec>
        <!-- a structural mapping: "in2:ContactListQuery/io2:Contact_spcList_spcQuery_spcWPS_spcCERN_ContactListQuery_Input/io:ListOfContactListWpsCern"(ListOfContactListWpsCern) to "io:ListOfContactListWpsCern"(ListOfContactListWpsCern) -->
        <xsl:copy-of select="in2:ContactListQuery/io2:Contact_spcList_spcQuery_spcWPS_spcCERN_ContactListQuery_Input/io:ListOfContactListWpsCern"/>
      </io2:Contact_spcList_spcQuery_spcWPS_spcCERN_ContactListQuery_Input>
    </body>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
